### ISSUE TITLE
can the bot copy embeds

### ISSUE THREAD

**Issue by dog-broad** [17jmalek98/discord-relay#1]
I've gone through the code
doesn't seem to be able to copy
but it will be great if it could, hope u can make it possible

**Comment by joshmalek** [comment]
This project is no longer being maintained, but I did include documentation in the READMEs.  Check out the Red V3 documentation, I'm sure copying embeds would be a very simple change.  Feel free to fork and contribute to the project, I would be more than willing to help out if you do decide to do a PR or some research into copying embeds. Here's Reds documentation: https://docs.discord.red/en/stable/

**Comment by dog-broad** [comment]
oh ok
lol I'll try my best to add the embed feature but I'm no developer and I'm pretty noob so help me if u can😅

**Comment by rushi12565** [comment]
oh ok
lol I'll try my best to add the embed feature but I'm no developer and I'm pretty noob so help me if u can😅

**Comment by joshmalek** [comment]
> oh ok
> lol I'll try my best to add the embed feature but I'm no developer and I'm pretty noob so help me if u can😅

Yeah no problem, you can add me on discord @ swine#4527 if you need any help

**Comment by dog-broad** [comment]
k cool

**Comment by dog-broad** [comment]
I could make it possible in python but I dint know nodejs that much 😂 lol
